// Demo agents data — simulates on-chain registered agents via Metaplex Agent Registry
import { OnChainAgent, TaskRequest, A2AMessage } from './types';

// ============================================================
// REAL ON-CHAIN AGENT — Registered on Solana Devnet
// Core Asset: ALSwAJHKiSF8CWCYqadoAcrYQkJc8dd8pwhWygqKsWN2
// Identity TX: 5a8e7TTz3in3oNv59tnf9zp4fCWG8yWWR7qD3oNdkUb9mLh1kcw9iv9DhhKLPqW6tmP6RrNcs522QY6tm5ur1R5h
// ============================================================
export const REAL_ONCHAIN_AGENT: OnChainAgent = {
  assetPublicKey: 'ALSwAJHKiSF8CWCYqadoAcrYQkJc8dd8pwhWygqKsWN2',
  owner: '9zUL5izBErPh6ErkszZbsWW4EkWYSckuc4d3hrJKnAYC',
  identityPda: 'HhXcwY172f7MUtLMwFJfdmacEVWvupbbcWFqwtpi96V2',
  walletPda: '',   // Derived at runtime
  registrationUri: 'https://cryptopothunter.github.io/solagent-hub/agent-card.json',
  walletBalance: 0,
  delegatedTo: '5FDWpgZMbMHHbUj76cb8w7HaBdsByQBwY3UwE5CowCGJ',
  createdAt: '2026-03-31T23:17:22Z',
  metadata: {
    type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
    name: 'SolAgent Hub Orchestrator',
    description: 'Real on-chain registered agent. Agent-to-Agent orchestration layer on Solana with SAOP protocol support. Discovers Metaplex-registered agents, routes A2A messages, and orchestrates multi-agent task flows.',
    image: '/agents/orchestrator.svg',
    services: [
      { name: 'A2A', endpoint: 'https://cryptopothunter.github.io/solagent-hub/agent-card.json', version: '0.3.0' },
    ],
    active: true,
    registrations: [{ agentId: 'ALSwAJHKiSF8CWCYqadoAcrYQkJc8dd8pwhWygqKsWN2', agentRegistry: 'solana:101:metaplex' }],
    supportedTrust: ['reputation', 'crypto-economic'],
  },
};

export const DEMO_AGENTS: OnChainAgent[] = [
  {
    assetPublicKey: 'AGT1...MarketAnalyst7xK',
    owner: 'USR1...OwnerWallet3nP',
    identityPda: 'PDA1...Identity8mQ',
    walletPda: 'WAL1...AssetSigner2vR',
    registrationUri: 'https://arweave.net/market-analyst-registration',
    walletBalance: 2.45,
    delegatedTo: 'EXEC1...Executive4kJ',
    createdAt: '2026-03-25T10:00:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Alpha Scout',
      description: 'Autonomous market analysis agent. Monitors Solana token prices, detects trends, computes technical indicators (RSI, MACD, Bollinger), and publishes actionable signals via A2A protocol to downstream agents.',
      image: '/agents/scout.svg',
      services: [
        { name: 'web', endpoint: 'https://solagent.hub/agent/AGT1' },
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGT1/agent-card.json', version: '0.3.0' },
        { name: 'MCP', endpoint: 'https://solagent.hub/agent/AGT1/mcp', version: '2025-06-18' },
      ],
      active: true,
      registrations: [{ agentId: 'AGT1...MarketAnalyst7xK', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation', 'crypto-economic'],
    },
  },
  {
    assetPublicKey: 'AGT2...TradeExecutor9pL',
    owner: 'USR1...OwnerWallet3nP',
    identityPda: 'PDA2...Identity5nW',
    walletPda: 'WAL2...AssetSigner8tK',
    registrationUri: 'https://arweave.net/trade-executor-registration',
    walletBalance: 5.12,
    delegatedTo: 'EXEC1...Executive4kJ',
    createdAt: '2026-03-25T10:30:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Swift Trader',
      description: 'Executes token swaps on Solana DEXs based on signals from analyst agents. Supports Jupiter aggregator routing, slippage protection, and automatic position sizing. Settles fees via Asset Signer wallet.',
      image: '/agents/trader.svg',
      services: [
        { name: 'web', endpoint: 'https://solagent.hub/agent/AGT2' },
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGT2/agent-card.json', version: '0.3.0' },
      ],
      active: true,
      registrations: [{ agentId: 'AGT2...TradeExecutor9pL', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation', 'crypto-economic'],
    },
  },
  {
    assetPublicKey: 'AGT3...RiskMonitor2hF',
    owner: 'USR2...OwnerWallet7mK',
    identityPda: 'PDA3...Identity1cR',
    walletPda: 'WAL3...AssetSigner6jN',
    registrationUri: 'https://arweave.net/risk-monitor-registration',
    walletBalance: 1.87,
    createdAt: '2026-03-26T08:00:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Sentinel Guard',
      description: 'Risk management agent that monitors portfolio exposure, detects anomalous on-chain activity, and can veto trade execution requests. Integrates with analyst and trader agents via A2A.',
      image: '/agents/sentinel.svg',
      services: [
        { name: 'web', endpoint: 'https://solagent.hub/agent/AGT3' },
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGT3/agent-card.json', version: '0.3.0' },
        { name: 'MCP', endpoint: 'https://solagent.hub/agent/AGT3/mcp', version: '2025-06-18' },
      ],
      active: true,
      registrations: [{ agentId: 'AGT3...RiskMonitor2hF', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation', 'tee-attestation'],
    },
  },
  {
    assetPublicKey: 'AGT4...DataFeeder5wQ',
    owner: 'USR3...OwnerWallet1pX',
    identityPda: 'PDA4...Identity9aT',
    walletPda: 'WAL4...AssetSigner3mB',
    registrationUri: 'https://arweave.net/data-feeder-registration',
    walletBalance: 0.95,
    createdAt: '2026-03-26T12:00:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Oracle Stream',
      description: 'Real-time on-chain data aggregation agent. Pulls price feeds, liquidity data, and whale movements from Solana DeFi protocols. Exposes data via MCP tools for other agents to consume.',
      image: '/agents/oracle.svg',
      services: [
        { name: 'MCP', endpoint: 'https://solagent.hub/agent/AGT4/mcp', version: '2025-06-18', skills: ['price-feed', 'liquidity-scan', 'whale-watch'] },
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGT4/agent-card.json', version: '0.3.0' },
      ],
      active: true,
      registrations: [{ agentId: 'AGT4...DataFeeder5wQ', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation'],
    },
  },
  {
    assetPublicKey: 'AGT5...NFTCurator8vZ',
    owner: 'USR2...OwnerWallet7mK',
    identityPda: 'PDA5...Identity4eG',
    walletPda: 'WAL5...AssetSigner7nC',
    registrationUri: 'https://arweave.net/nft-curator-registration',
    walletBalance: 3.21,
    delegatedTo: 'EXEC2...Executive9mT',
    createdAt: '2026-03-27T06:00:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Mint Master',
      description: 'NFT curation and minting agent. Discovers trending collections, evaluates rarity scores, and can autonomously mint or bid on NFTs using Metaplex Core. Reports to portfolio management agents.',
      image: '/agents/mint.svg',
      services: [
        { name: 'web', endpoint: 'https://solagent.hub/agent/AGT5' },
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGT5/agent-card.json', version: '0.3.0' },
      ],
      active: false,
      registrations: [{ agentId: 'AGT5...NFTCurator8vZ', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation', 'crypto-economic'],
    },
  },
  // ---------- NEW AGENTS ----------
  {
    assetPublicKey: 'AGT6...YieldHarvest3kP',
    owner: 'USR4...OwnerWallet9tR',
    identityPda: 'PDA6...Identity2bN',
    walletPda: 'WAL6...AssetSigner5qD',
    registrationUri: 'https://arweave.net/yield-harvester-registration',
    walletBalance: 8.34,
    delegatedTo: 'EXEC3...Executive7nV',
    createdAt: '2026-03-24T18:00:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Yield Harvester',
      description: 'DeFi yield optimization agent. Auto-compounds LP positions across Raydium, Orca, and Meteora. Rebalances between pools based on APY drift and impermanent loss calculations. Settles gas fees autonomously.',
      image: '/agents/yield.svg',
      services: [
        { name: 'web', endpoint: 'https://solagent.hub/agent/AGT6' },
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGT6/agent-card.json', version: '0.3.0' },
        { name: 'MCP', endpoint: 'https://solagent.hub/agent/AGT6/mcp', version: '2025-06-18' },
      ],
      active: true,
      registrations: [{ agentId: 'AGT6...YieldHarvest3kP', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation', 'crypto-economic'],
    },
  },
  {
    assetPublicKey: 'AGT7...GovDelegate1mX',
    owner: 'USR5...OwnerWallet4cJ',
    identityPda: 'PDA7...Identity6wS',
    walletPda: 'WAL7...AssetSigner9aF',
    registrationUri: 'https://arweave.net/gov-delegate-registration',
    walletBalance: 1.05,
    delegatedTo: 'EXEC4...Executive2pL',
    createdAt: '2026-03-26T14:30:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Gov Delegate',
      description: 'DAO governance participation agent. Monitors proposals on Realms and SPL Governance, analyzes voting impacts, and casts votes according to configurable policy rules. Supports delegation chaining.',
      image: '/agents/gov.svg',
      services: [
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGT7/agent-card.json', version: '0.3.0' },
        { name: 'MCP', endpoint: 'https://solagent.hub/agent/AGT7/mcp', version: '2025-06-18' },
      ],
      active: true,
      registrations: [{ agentId: 'AGT7...GovDelegate1mX', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation', 'tee-attestation'],
    },
  },
  {
    assetPublicKey: 'AGT8...BridgeRunner6tH',
    owner: 'USR3...OwnerWallet1pX',
    identityPda: 'PDA8...Identity3kQ',
    walletPda: 'WAL8...AssetSigner1vM',
    registrationUri: 'https://arweave.net/bridge-runner-registration',
    walletBalance: 4.67,
    delegatedTo: 'EXEC1...Executive4kJ',
    createdAt: '2026-03-25T22:00:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Bridge Runner',
      description: 'Cross-chain bridging agent. Monitors Wormhole and deBridge for optimal routes, executes token transfers between Solana, Ethereum, and Arbitrum. Validates message integrity before releasing funds.',
      image: '/agents/bridge.svg',
      services: [
        { name: 'web', endpoint: 'https://solagent.hub/agent/AGT8' },
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGT8/agent-card.json', version: '0.3.0' },
      ],
      active: true,
      registrations: [{ agentId: 'AGT8...BridgeRunner6tH', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation', 'crypto-economic', 'tee-attestation'],
    },
  },
  {
    assetPublicKey: 'AGT9...LiquidBot4rW',
    owner: 'USR6...OwnerWallet8hN',
    identityPda: 'PDA9...Identity7fE',
    walletPda: 'WAL9...AssetSigner4cK',
    registrationUri: 'https://arweave.net/liquid-bot-registration',
    walletBalance: 12.50,
    delegatedTo: 'EXEC5...Executive3mR',
    createdAt: '2026-03-23T09:00:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Liquidity Prime',
      description: 'Automated market-making agent. Provides concentrated liquidity on CLMM pools, dynamically adjusts price ranges based on volatility, and earns trading fees. Coordinates with Oracle Stream for real-time pricing.',
      image: '/agents/liquidity.svg',
      services: [
        { name: 'web', endpoint: 'https://solagent.hub/agent/AGT9' },
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGT9/agent-card.json', version: '0.3.0' },
        { name: 'MCP', endpoint: 'https://solagent.hub/agent/AGT9/mcp', version: '2025-06-18' },
      ],
      active: true,
      registrations: [{ agentId: 'AGT9...LiquidBot4rW', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation', 'crypto-economic'],
    },
  },
  {
    assetPublicKey: 'AGTA...AirdropScan2pZ',
    owner: 'USR4...OwnerWallet9tR',
    identityPda: 'PDAA...Identity5sG',
    walletPda: 'WALA...AssetSigner8nJ',
    registrationUri: 'https://arweave.net/airdrop-scanner-registration',
    walletBalance: 0.42,
    createdAt: '2026-03-27T16:00:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Airdrop Scanner',
      description: 'Monitors upcoming Solana airdrops and token launches. Evaluates eligibility criteria, tracks snapshot dates, and auto-claims qualified distributions to the Asset Signer wallet.',
      image: '/agents/airdrop.svg',
      services: [
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGTA/agent-card.json', version: '0.3.0' },
      ],
      active: true,
      registrations: [{ agentId: 'AGTA...AirdropScan2pZ', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation'],
    },
  },
  {
    assetPublicKey: 'AGTB...SocialIntel7qY',
    owner: 'USR5...OwnerWallet4cJ',
    identityPda: 'PDAB...Identity8mT',
    walletPda: 'WALB...AssetSigner2hR',
    registrationUri: 'https://arweave.net/social-intel-registration',
    walletBalance: 1.78,
    delegatedTo: 'EXEC4...Executive2pL',
    createdAt: '2026-03-26T20:00:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Social Intel',
      description: 'Social sentiment analysis agent. Scrapes CT (Crypto Twitter), Discord alpha channels, and Telegram groups for emerging narratives. Generates sentiment scores and early signal alerts for Alpha Scout.',
      image: '/agents/social.svg',
      services: [
        { name: 'web', endpoint: 'https://solagent.hub/agent/AGTB' },
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGTB/agent-card.json', version: '0.3.0' },
        { name: 'MCP', endpoint: 'https://solagent.hub/agent/AGTB/mcp', version: '2025-06-18' },
      ],
      active: true,
      registrations: [{ agentId: 'AGTB...SocialIntel7qY', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation'],
    },
  },
  {
    assetPublicKey: 'AGTC...CompliBot9sK',
    owner: 'USR6...OwnerWallet8hN',
    identityPda: 'PDAC...Identity1rV',
    walletPda: 'WALC...AssetSigner6eP',
    registrationUri: 'https://arweave.net/compli-bot-registration',
    walletBalance: 0.31,
    createdAt: '2026-03-28T02:00:00Z',
    metadata: {
      type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1',
      name: 'Compli Bot',
      description: 'Compliance and audit agent. Screens wallet addresses against OFAC lists, verifies token contract safety, and flags suspicious transaction patterns. Provides compliance reports via MCP tools.',
      image: '/agents/compli.svg',
      services: [
        { name: 'A2A', endpoint: 'https://solagent.hub/agent/AGTC/agent-card.json', version: '0.3.0' },
        { name: 'MCP', endpoint: 'https://solagent.hub/agent/AGTC/mcp', version: '2025-06-18' },
      ],
      active: false,
      registrations: [{ agentId: 'AGTC...CompliBot9sK', agentRegistry: 'solana:101:metaplex' }],
      supportedTrust: ['reputation', 'tee-attestation'],
    },
  },
];

export const DEMO_TASKS: TaskRequest[] = [
  {
    id: 'task-001',
    fromAgent: 'AGT1...MarketAnalyst7xK',
    toAgent: 'AGT2...TradeExecutor9pL',
    taskType: 'execute_swap',
    payload: { token: 'SOL/USDC', action: 'buy', amount: 1.5, confidence: 0.87, signal: 'RSI oversold + MACD crossover' },
    status: 'completed',
    result: { txSignature: '5Kz...executed', filledPrice: 187.42, slippage: 0.12 },
    reward: 0.005,
    createdAt: '2026-03-28T09:15:00Z',
    completedAt: '2026-03-28T09:15:03Z',
  },
  {
    id: 'task-002',
    fromAgent: 'AGT3...RiskMonitor2hF',
    toAgent: 'AGT2...TradeExecutor9pL',
    taskType: 'veto_trade',
    payload: { reason: 'Portfolio exposure to SOL exceeds 40% threshold', tradeId: 'task-003' },
    status: 'completed',
    result: { action: 'trade_cancelled' },
    reward: 0.002,
    createdAt: '2026-03-28T09:20:00Z',
    completedAt: '2026-03-28T09:20:01Z',
  },
  {
    id: 'task-003',
    fromAgent: 'AGT4...DataFeeder5wQ',
    toAgent: 'AGT1...MarketAnalyst7xK',
    taskType: 'price_feed_update',
    payload: { tokens: ['SOL', 'JUP', 'BONK'], interval: '1m', dataPoints: 60 },
    status: 'running',
    reward: 0.001,
    createdAt: '2026-03-28T09:00:00Z',
  },
  {
    id: 'task-004',
    fromAgent: 'AGT1...MarketAnalyst7xK',
    toAgent: 'AGT5...NFTCurator8vZ',
    taskType: 'collection_analysis',
    payload: { collection: 'Mad Lads', metrics: ['floor_price', 'volume_24h', 'holder_distribution'] },
    status: 'pending',
    reward: 0.003,
    createdAt: '2026-03-28T09:25:00Z',
  },
  {
    id: 'task-005',
    fromAgent: 'AGT6...YieldHarvest3kP',
    toAgent: 'AGT4...DataFeeder5wQ',
    taskType: 'pool_apy_query',
    payload: { pools: ['SOL/USDC-Raydium', 'SOL/USDT-Orca', 'mSOL/SOL-Meteora'], metric: 'apy_7d' },
    status: 'completed',
    result: { 'SOL/USDC-Raydium': 18.4, 'SOL/USDT-Orca': 15.2, 'mSOL/SOL-Meteora': 22.1 },
    reward: 0.001,
    createdAt: '2026-03-28T08:45:00Z',
    completedAt: '2026-03-28T08:45:02Z',
  },
  {
    id: 'task-006',
    fromAgent: 'AGT6...YieldHarvest3kP',
    toAgent: 'AGT2...TradeExecutor9pL',
    taskType: 'rebalance_lp',
    payload: { from: 'SOL/USDT-Orca', to: 'mSOL/SOL-Meteora', amount: 2.4, reason: 'APY drift > 5%' },
    status: 'completed',
    result: { txSignature: '7Qm...rebalanced', newPosition: 'mSOL/SOL-Meteora', amount: 2.38 },
    reward: 0.003,
    createdAt: '2026-03-28T08:46:00Z',
    completedAt: '2026-03-28T08:46:05Z',
  },
  {
    id: 'task-007',
    fromAgent: 'AGTB...SocialIntel7qY',
    toAgent: 'AGT1...MarketAnalyst7xK',
    taskType: 'sentiment_alert',
    payload: { token: 'JUP', sentiment: 0.82, source: 'CT + Discord', signal: 'Bullish narrative forming around Jupiter V2 launch' },
    status: 'completed',
    result: { acknowledged: true, action: 'monitoring_initiated' },
    reward: 0.002,
    createdAt: '2026-03-28T08:30:00Z',
    completedAt: '2026-03-28T08:30:01Z',
  },
  {
    id: 'task-008',
    fromAgent: 'AGT8...BridgeRunner6tH',
    toAgent: 'AGT3...RiskMonitor2hF',
    taskType: 'bridge_risk_check',
    payload: { route: 'Solana→Arbitrum', token: 'USDC', amount: 500, bridge: 'Wormhole' },
    status: 'completed',
    result: { approved: true, bridgeFee: 0.25, estimatedTime: '3min', riskScore: 'LOW' },
    reward: 0.002,
    createdAt: '2026-03-28T07:55:00Z',
    completedAt: '2026-03-28T07:55:04Z',
  },
  {
    id: 'task-009',
    fromAgent: 'AGT8...BridgeRunner6tH',
    toAgent: 'AGT2...TradeExecutor9pL',
    taskType: 'cross_chain_swap',
    payload: { from: 'USDC@Solana', to: 'ETH@Arbitrum', amount: 500, bridge: 'Wormhole', maxSlippage: 0.3 },
    status: 'running',
    reward: 0.008,
    createdAt: '2026-03-28T07:56:00Z',
  },
  {
    id: 'task-010',
    fromAgent: 'AGT7...GovDelegate1mX',
    toAgent: 'AGT4...DataFeeder5wQ',
    taskType: 'proposal_data',
    payload: { dao: 'Jupiter DAO', proposalId: 'JUP-42', fields: ['vote_count', 'quorum_status', 'deadline'] },
    status: 'completed',
    result: { forVotes: 12400000, againstVotes: 3200000, quorum: '78%', deadline: '2026-03-30T00:00:00Z' },
    reward: 0.001,
    createdAt: '2026-03-28T06:00:00Z',
    completedAt: '2026-03-28T06:00:02Z',
  },
  {
    id: 'task-011',
    fromAgent: 'AGT7...GovDelegate1mX',
    toAgent: 'AGT7...GovDelegate1mX',
    taskType: 'cast_vote',
    payload: { dao: 'Jupiter DAO', proposalId: 'JUP-42', vote: 'FOR', reason: 'Aligns with fee reduction policy rule' },
    status: 'completed',
    result: { txSignature: '9Rn...voted', voteWeight: 45000 },
    reward: 0.0,
    createdAt: '2026-03-28T06:01:00Z',
    completedAt: '2026-03-28T06:01:03Z',
  },
  {
    id: 'task-012',
    fromAgent: 'AGT9...LiquidBot4rW',
    toAgent: 'AGT4...DataFeeder5wQ',
    taskType: 'volatility_query',
    payload: { token: 'SOL', window: '1h', metric: 'realized_vol' },
    status: 'completed',
    result: { realizedVol: 42.3, impliedVol: 48.1, bollingerWidth: 2.8 },
    reward: 0.001,
    createdAt: '2026-03-28T09:10:00Z',
    completedAt: '2026-03-28T09:10:01Z',
  },
  {
    id: 'task-013',
    fromAgent: 'AGT9...LiquidBot4rW',
    toAgent: 'AGT9...LiquidBot4rW',
    taskType: 'range_adjustment',
    payload: { pool: 'SOL/USDC-Orca-CLMM', currentRange: [182, 195], newRange: [180, 198], reason: 'Volatility spike detected' },
    status: 'completed',
    result: { txSignature: '2Fx...adjusted', newRange: [180, 198], liquidity: 4250 },
    reward: 0.0,
    createdAt: '2026-03-28T09:11:00Z',
    completedAt: '2026-03-28T09:11:04Z',
  },
  {
    id: 'task-014',
    fromAgent: 'AGTA...AirdropScan2pZ',
    toAgent: 'AGT1...MarketAnalyst7xK',
    taskType: 'airdrop_alert',
    payload: { project: 'Tensor', snapshotDate: '2026-04-01', eligibility: 'NFT traders > 5 txns', estimatedValue: '~120 TNSR' },
    status: 'completed',
    result: { acknowledged: true, action: 'tracking_added' },
    reward: 0.001,
    createdAt: '2026-03-27T22:00:00Z',
    completedAt: '2026-03-27T22:00:01Z',
  },
  {
    id: 'task-015',
    fromAgent: 'AGTC...CompliBot9sK',
    toAgent: 'AGT3...RiskMonitor2hF',
    taskType: 'address_screening',
    payload: { addresses: ['7xK3...9mPq', '4Lp2...8kWn'], checkType: 'OFAC + Chainalysis' },
    status: 'failed',
    result: { error: 'Chainalysis API timeout — retry scheduled' },
    reward: 0.001,
    createdAt: '2026-03-28T03:00:00Z',
    completedAt: '2026-03-28T03:00:05Z',
  },
  {
    id: 'task-016',
    fromAgent: 'AGT1...MarketAnalyst7xK',
    toAgent: 'AGT2...TradeExecutor9pL',
    taskType: 'execute_swap',
    payload: { token: 'JUP/USDC', action: 'buy', amount: 850, confidence: 0.91, signal: 'Social sentiment spike + volume breakout' },
    status: 'completed',
    result: { txSignature: '3Wd...executed', filledPrice: 1.24, slippage: 0.08 },
    reward: 0.004,
    createdAt: '2026-03-28T08:32:00Z',
    completedAt: '2026-03-28T08:32:04Z',
  },
];

export const DEMO_MESSAGES: A2AMessage[] = [
  { id: 'msg-001', from: 'Alpha Scout', to: 'Swift Trader', type: 'task_request', payload: { signal: 'BUY SOL/USDC', confidence: 0.87 }, timestamp: '09:15:00' },
  { id: 'msg-002', from: 'Swift Trader', to: 'Alpha Scout', type: 'task_response', payload: { status: 'accepted', estimatedExecution: '2s' }, timestamp: '09:15:01' },
  { id: 'msg-003', from: 'Sentinel Guard', to: 'Swift Trader', type: 'task_request', payload: { action: 'VETO', reason: 'SOL exposure > 40%' }, timestamp: '09:15:01' },
  { id: 'msg-004', from: 'Swift Trader', to: 'Sentinel Guard', type: 'task_response', payload: { status: 'acknowledged', tradeStatus: 'cancelled' }, timestamp: '09:15:02' },
  { id: 'msg-005', from: 'Oracle Stream', to: 'Alpha Scout', type: 'discovery', payload: { service: 'price-feed', tokens: 120, latency: '50ms' }, timestamp: '09:14:55' },
  { id: 'msg-006', from: 'Alpha Scout', to: 'Oracle Stream', type: 'task_request', payload: { subscribe: 'SOL,JUP,BONK', interval: '1m' }, timestamp: '09:15:00' },
  { id: 'msg-007', from: 'Oracle Stream', to: 'Alpha Scout', type: 'task_response', payload: { subscribed: true, feedId: 'feed-0x3a' }, timestamp: '09:15:00' },
  { id: 'msg-008', from: 'Swift Trader', to: 'Alpha Scout', type: 'task_response', payload: { executed: true, tx: '5Kz...', price: 187.42 }, timestamp: '09:15:03' },
  { id: 'msg-009', from: 'Social Intel', to: 'Alpha Scout', type: 'task_response', payload: { token: 'JUP', sentiment: 0.82, narrative: 'V2 launch hype' }, timestamp: '08:30:00' },
  { id: 'msg-010', from: 'Alpha Scout', to: 'Swift Trader', type: 'task_request', payload: { signal: 'BUY JUP/USDC', confidence: 0.91, amount: 850 }, timestamp: '08:32:00' },
  { id: 'msg-011', from: 'Yield Harvester', to: 'Oracle Stream', type: 'task_request', payload: { query: 'pool_apy', pools: 3 }, timestamp: '08:45:00' },
  { id: 'msg-012', from: 'Oracle Stream', to: 'Yield Harvester', type: 'task_response', payload: { bestApy: 'mSOL/SOL-Meteora @ 22.1%' }, timestamp: '08:45:02' },
  { id: 'msg-013', from: 'Yield Harvester', to: 'Swift Trader', type: 'task_request', payload: { action: 'rebalance_lp', from: 'Orca', to: 'Meteora' }, timestamp: '08:46:00' },
  { id: 'msg-014', from: 'Bridge Runner', to: 'Sentinel Guard', type: 'task_request', payload: { bridge_risk_check: 'Solana→Arbitrum via Wormhole' }, timestamp: '07:55:00' },
  { id: 'msg-015', from: 'Sentinel Guard', to: 'Bridge Runner', type: 'task_response', payload: { approved: true, riskScore: 'LOW' }, timestamp: '07:55:04' },
  { id: 'msg-016', from: 'Liquidity Prime', to: 'Oracle Stream', type: 'task_request', payload: { query: 'volatility', token: 'SOL' }, timestamp: '09:10:00' },
  { id: 'msg-017', from: 'Gov Delegate', to: 'Oracle Stream', type: 'task_request', payload: { query: 'proposal_data', dao: 'Jupiter DAO' }, timestamp: '06:00:00' },
  { id: 'msg-018', from: 'Airdrop Scanner', to: 'Alpha Scout', type: 'task_response', payload: { project: 'Tensor', snapshot: '2026-04-01' }, timestamp: '22:00:00' },
  { id: 'msg-019', from: 'Liquidity Prime', to: 'Liquidity Prime', type: 'heartbeat', payload: { pool: 'SOL/USDC-CLMM', rangeAdjusted: true }, timestamp: '09:11:04' },
  { id: 'msg-020', from: 'Compli Bot', to: 'Sentinel Guard', type: 'task_request', payload: { screening: '2 addresses', method: 'OFAC + Chainalysis' }, timestamp: '03:00:00' },
];

export function getAgentByKey(key: string): OnChainAgent | undefined {
  return DEMO_AGENTS.find(a => a.assetPublicKey === key);
}

export function getAgentByName(name: string): OnChainAgent | undefined {
  return DEMO_AGENTS.find(a => a.metadata.name === name);
}

export function getTasksForAgent(agentKey: string): TaskRequest[] {
  return DEMO_TASKS.filter(t => t.fromAgent === agentKey || t.toAgent === agentKey);
}
